package statemachine.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import statemachine.behavior.State_Behavior;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import statemachine.behavior.StateMachine_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import statemachine.behavior.TransitionCondition_Behavior;
import jetbrains.mps.typesystem.inference.TypeChecker;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_6463807888000038946(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6463807888000048515(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return State_Behavior.call_getEnumNodeName_6463807888000048393(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_4332044356532225235(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "final");
  }

  public static Object referenceMacro_GetReferent_6463807888000056014(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return INamedConcept_Behavior.call_getFqName_1213877404258(SLinkOperations.getTarget(_context.getNode(), "stateMachine", false));
  }

  public static Object referenceMacro_GetReferent_7490299935948559025(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return INamedConcept_Behavior.call_getFqName_1213877404258(SLinkOperations.getTarget(_context.getNode(), "stateMchine", false));
  }

  public static Object referenceMacro_GetReferent_2903037320963916769(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return StateMachine_Behavior.getNextTokenName_2903037320963916761();
  }

  public static Object referenceMacro_GetReferent_2903037320963909122(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return StateMachine_Behavior.getInStateOperationName_2903037320963909190();
  }

  public static Object referenceMacro_GetReferent_8827301838529893777(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    String result = INamedConcept_Behavior.call_getFqName_1213877404258(SNodeOperations.as(SNodeOperations.getParent(_context.getNode()), "statemachine.structure.StateMachine")) + "." + StateMachine_Behavior.getStatesEnumValue_2903037320963909195();
    return result;
  }

  public static Object referenceMacro_GetReferent_8827301838529893780(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    String result = State_Behavior.call_getEnumNodeName_6463807888000048393(_context.getNode());
    return result;
  }

  public static Object referenceMacro_GetReferent_4332044356532254253(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return StateMachine_Behavior.getIsInFinalStateName_4332044356532254245();
  }

  public static boolean ifMacro_Condition_4332044356532190507(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "do", true) != null);
  }

  public static boolean ifMacro_Condition_1137392448294771859(final IOperationContext operationContext, final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "transition", true)).isNotEmpty();
  }

  public static SNode sourceNodeQuery_6463807888000056000(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "type", true);
  }

  public static SNode sourceNodeQuery_2903037320963944611(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "type", true);
  }

  public static SNode sourceNodeQuery_8398986181275323647(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "initialState", true);
  }

  public static SNode sourceNodeQuery_7490299935948559102(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expression", true);
  }

  public static SNode sourceNodeQuery_2903037320963924946(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "state", false);
  }

  public static SNode sourceNodeQuery_871947940434834387(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return TransitionCondition_Behavior.call_getConditionType_871947940434887993(SLinkOperations.getTarget(_context.getNode(), "expected", true));
  }

  public static SNode sourceNodeQuery_871947940434888199(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return TransitionCondition_Behavior.call_getExpression_871947940434888344(SLinkOperations.getTarget(_context.getNode(), "expected", true));
  }

  public static SNode sourceNodeQuery_1137392448294772676(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "transitToState", false);
  }

  public static SNode sourceNodeQuery_871947940434888481(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expected", true);
  }

  public static SNode sourceNodeQuery_4332044356532161012(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return TypeChecker.getInstance().getTypeOf(SLinkOperations.getTarget(_context.getNode(), "do", true));
  }

  public static SNode sourceNodeQuery_8272868549379783661(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "do", true);
  }

  public static Iterable sourceNodesQuery_2903037320963925357(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return StateMachine_Behavior.call_getAllStates_2903037320963927292(_context.getNode());
  }

  public static Iterable sourceNodesQuery_6463807888000048233(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return StateMachine_Behavior.call_getAllStates_2903037320963927292(_context.getNode());
  }

  public static Iterable sourceNodesQuery_1137392448294771780(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "transition", true);
  }
}
