package statemachine.sandbox.sandbox;

/*Generated by MPS */


public class Ma {
  private Ma.MachineState currentState;

  public Ma() {
    currentState = statemachine.sandbox.sandbox.Ma.MachineState.ff;
  }

  public void addNextToken(String token) {
    currentState = getNextState(token);
  }

  private Ma.MachineState getNextState(String token) {
    switch (currentState) {
      case ff:
        
        if (token.equals("  ")) {
          return isInState();
        };
        break;
      default:
    }
    throw new IllegalArgumentException("bad token: " + token);
  }

  public boolean isInState(Ma.MachineState state) {
    return currentState == state;
  }

  public static   enum MachineState {
    ff();

    MachineState() {
    }
  }
}
