package statemachine.sandbox.sandbox;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;

public class Ma {
  private Ma.MachineState currentState;

  public Ma() {
    currentState = statemachine.sandbox.sandbox.Ma.MachineState.onlyA;
  }

  public void addNextToken(String token) {
    currentState = getNextState(token);
  }

  private Ma.MachineState getNextState(String token) {
    switch (currentState) {
      case aOrB:
        {
          _FunctionTypes._return_P1_E0<? extends Boolean, ? super String> condition = new _FunctionTypes._return_P1_E0<Boolean, String>() {
            public Boolean invoke(String it) {
              return Main.isOk(it);
            }
          };
          if (condition.invoke(token)) {
            return statemachine.sandbox.sandbox.Ma.MachineState.aOrB;
          }
        }
        {
          String condition = "b";
          if (token.equals(condition)) {
            
            {
              _FunctionTypes._void_P1_E0<? super String> onChange = new _FunctionTypes._void_P1_E0<String>() {
                public void invoke(String it) {
                  System.out.println("do anything!");
                }
              };
              onChange.invoke(token);
            };
            return statemachine.sandbox.sandbox.Ma.MachineState.onlyB;
          }
        }
        break;
      case onlyB:
        {
          String condition = "b";
          if (token.equals(condition)) {
            return statemachine.sandbox.sandbox.Ma.MachineState.onlyB;
          }
        }
        break;
      case onlyA:
        {
          String condition = "a";
          if (token.equals(condition)) {
            
            {
              _FunctionTypes._void_P1_E0<? super String> onChange = new _FunctionTypes._void_P1_E0<String>() {
                public void invoke(String it) {
                  System.out.println(it);
                }
              };
              onChange.invoke(token);
            };
            return statemachine.sandbox.sandbox.Ma.MachineState.aOrB;
          }
        }
        break;
      default:
    }
    throw new IllegalArgumentException("bad token: " + token);
  }

  public boolean isInState(Ma.MachineState state) {
    return currentState == state;
  }

  public boolean isInFinalState() {
    return currentState.isFinal;
  }

  public static   enum MachineState {
    aOrB(false),
    onlyB(true),
    onlyA(false);

    /*package*/ final boolean isFinal;

    MachineState(boolean isFinal) {
      this.isFinal = isFinal;
    }
  }
}
