package statemachine.sandbox.sandbox;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;

public class Main {
  public Main() {
    System.out.println("");
    new _FunctionTypes._return_P1_E0<Boolean, String>() {
      public Boolean invoke(String s) {
        return true;
      }
    }.invoke("");
    Ma sm = new Ma();
    sm.addNextToken("hello");
  }
}
