package statemachine.sandbox.sandbox;

/*Generated by MPS */

import statemachine.sandbox.sandbox.Ma.MachineState;

public class Main {
  public Main() {
  }

  public static void main(String[] args) {
    System.out.println("");
    Ma sm = new Ma();
    String inputString = "aaabb";
    for (int i = 0; i < inputString.length(); i++) {
      sm.addNextToken(inputString.substring(i, i + 1));
    }
    sm.isInFinalState();
    System.out.println(sm.isInState(MachineState.onlyB));
  }

  public static boolean isOk(String s) {
    return true;
  }
}
