package statemachine.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Statemachine_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("8e26153e-fabf-47e0-92e3-9aff2ccf1b88(statemachine)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
