package statemachine.behavior;

/*Generated by MPS */


public class AddNextTokenOperation_BehaviorDescriptor extends StateMachineOperation_BehaviorDescriptor {
  public AddNextTokenOperation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statemachine.structure.AddNextTokenOperation";
  }
}
