package statemachine.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"statemachine.structure.ClojureTransitionCondition", "statemachine.structure.EqualsTransitionCondition", "statemachine.structure.State", "statemachine.structure.StateMachineCreator", "statemachine.structure.StateMachineDeclaration", "statemachine.structure.StateMachineType", "statemachine.structure.StateType", "statemachine.structure.Transition"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 4:
        return new StateMachineDeclaration_BehaviorDescriptor();
      case 2:
        return new State_BehaviorDescriptor();
      case 7:
        return new Transition_BehaviorDescriptor();
      case 5:
        return new StateMachineType_BehaviorDescriptor();
      case 3:
        return new StateMachineCreator_BehaviorDescriptor();
      case 6:
        return new StateType_BehaviorDescriptor();
      case 1:
        return new EqualsTransitionCondition_BehaviorDescriptor();
      case 0:
        return new ClojureTransitionCondition_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
