package statemachine.behavior;

/*Generated by MPS */


public class ClojureTransitionCondition_BehaviorDescriptor extends TransitionCondition_BehaviorDescriptor {
  public ClojureTransitionCondition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statemachine.structure.ClojureTransitionCondition";
  }
}
