package statemachine.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeChecker;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class ClojureTransitionCondition_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getConditionType_871947940434887993(SNode thisNode) {
    return TypeChecker.getInstance().getTypeOf(SLinkOperations.getTarget(thisNode, "expression", true));
  }

  public static SNode virtual_getExpression_871947940434888344(SNode thisNode) {
    return SLinkOperations.getTarget(thisNode, "expression", true);
  }
}
