package statemachine.behavior;

/*Generated by MPS */


public class EqualsTransitionCondition_BehaviorDescriptor extends TransitionCondition_BehaviorDescriptor {
  public EqualsTransitionCondition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statemachine.structure.EqualsTransitionCondition";
  }
}
