package statemachine.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class EqualsTransitionCondition_BehaviorDescriptor extends TransitionCondition_BehaviorDescriptor {
  public EqualsTransitionCondition_BehaviorDescriptor() {
  }

  public SNode virtual_getExpression_871947940434888344(SNode thisNode) {
    return EqualsTransitionCondition_Behavior.virtual_getExpression_871947940434888344(thisNode);
  }

  public SNode virtual_getConditionType_871947940434887993(SNode thisNode) {
    return EqualsTransitionCondition_Behavior.virtual_getConditionType_871947940434887993(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "statemachine.structure.EqualsTransitionCondition";
  }
}
