package statemachine.behavior;

/*Generated by MPS */


public class IsInFinalStateOperation_BehaviorDescriptor extends StateMachineOperation_BehaviorDescriptor {
  public IsInFinalStateOperation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statemachine.structure.IsInFinalStateOperation";
  }
}
