package statemachine.behavior;

/*Generated by MPS */


public class IsInStateOperation_BehaviorDescriptor extends StateMachineOperation_BehaviorDescriptor {
  public IsInStateOperation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statemachine.structure.IsInStateOperation";
  }
}
