package statemachine.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Type_BehaviorDescriptor;

public class StateType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public StateType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statemachine.structure.StateType";
  }
}
