package statemachine.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class State_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String call_getEnumNodeName_6463807888000048393(SNode thisNode) {
    System.out.println(thisNode);
    System.out.println(SPropertyOperations.getString(thisNode, "name"));
    return SPropertyOperations.getString(thisNode, "name");
  }
}
