package statemachine.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.AbstractCreator_BehaviorDescriptor;

public class StateMachineCreator_BehaviorDescriptor extends AbstractCreator_BehaviorDescriptor {
  public StateMachineCreator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statemachine.structure.StateMachineCreator";
  }
}
