package statemachine.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class StateMachine_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getUnitName_5067982036267369911(SNode thisNode) {
    return INamedConcept_Behavior.call_getFqName_1213877404258(thisNode);
  }

  public static String virtual_getPresentation_1213877396640(SNode thisNode) {
    return SPropertyOperations.getString(thisNode, "name");
  }
}
