package statemachine.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public abstract class TransitionCondition_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TransitionCondition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statemachine.structure.TransitionCondition";
  }

  public abstract SNode virtual_getConditionType_871947940434887993(SNode thisNode);

  public abstract SNode virtual_getExpression_871947940434888344(SNode thisNode);
}
