package statemachine.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class TransitionCondition_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TransitionCondition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "statemachine.structure.TransitionCondition";
  }
}
